spring:
  application:
    name: user-service
  config:
    import: optional:configserver:http://localhost:8888
server:
  port: 8082

EUREKA:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true



#h2database
#spring.h2.console.enabled=true
#server.port=8082
#spring.h2.console.path=/h2-console
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=password
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect


#spspring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#server.port=8082
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.jpa.hibernate.ddl-auto=create
#management.endpoints.web.exposure.include=*
#endpoint.health.show-details=alwaysring.datasource.url=jdbc:h2:mem:testdb


#POSTGRESS SQL

#spring.datasource.url=jdbc:postgresql://localhost:5432/userdb
#server.port=8082
#spring.datasource.username=embarkx
#spring.datasource.password=embarkx
#spring.datasource.jpa.database=POSTGRESQL
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#logging.level.org.springframework.web=DEBUG
#logging.level.org.springframework.http.converter=DEBUG

#Connect to MangoDB

#spring.data.mongodb.uri=mongodb+srv://ningaraj2t:XPpwTDeu2W3u9Z5J@usersdata.fyqz2ug.mongodb.net/?retryWrites=true&w=majority&appName=usersdata
#spring.data.mongodb.database=usersdb
#logging.level.org.springframework.data.mongodb.core.MongoTemplate=TRACE

#Connect to local mangoDB

#spring.data.mongodb.uri=mongodb://localhost:27017/usersdb
#spring.data.mongodb.database=usersdb
#logging.level.org.springframework.data.mongodb.core.MongoTemplate=TRACE
#server.port=8082

##connecting remote  postgres sql data base in cloud
#
#spring.datasource.url=jdbc:postgresql://ep-holy-bird-a5cbjjg3-pooler.us-east-2.aws.neon.tech/product?sslmode=require
#server.port=8082
#spring.datasource.username=product_owner
#spring.datasource.password=npg_MRso21XYUIGv
#spring.datasource.jpa.database=POSTGRESQL
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#logging.level.org.springframework.web=DEBUG
#logging.level.org.springframework.http.converter=DEBUG