spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: application-product-service
  datasource:
    url: jdbc:postgresql://localhost:5432/order
    username: embarkx
    password: embarkx
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect


server:
  port: 8083

logging:
  level:
    org:
      springframework:
        web: DEBUG
        http:
          converter: DEBUG






#spring.application.name=order
#h2database
#spring.h2.console.enabled=true
#server.port=8083
#spring.h2.console.path=/h2-console
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=password
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect


#POSTGRESS SQL

#spring.datasource.url=jdbc:postgresql://localhost:5432/order
#server.port=8083
#spring.datasource.username=embarkx
#spring.datasource.password=embarkx
#spring.datasource.jpa.database=POSTGRESQL
#spring.datasource.driver-class-name=org.postgresql.Driver
##spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#logging.level.org.springframework.web=DEBUG
#logging.level.org.springframework.http.converter=DEBUG

