---

spring:
  data:
    mongodb:
      uri: ${MONGO_URI}
      database: usersdb


server:
  port: 8082

EUREKA:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

logging:
  file:
    name: logs/${spring.application.name}.log
  logback:
    rollingpolicy:
      max-file-size: 5MB
      max-history: 30

#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/userdb
#    username: embarkx
#    password: embarkx
#    jpa:
#      database: POSTGRESQL
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#
#server:
#  port: 8082
#
#logging:
#  level:
#    org.springframework.web: DEBUG
#    org.springframework.http.converter: DEBUG
