#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/order
#
#    username: ${DB_USER}
#    password: ${DB_PASSWORD}
#    driver-class-name: org.postgresql.Driver
#    rabbitmq:
#      host: localhost
#      port: 5672
#      username: guest
#      password: guest
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#
#server:
#  port: 8083
#
#logging:
#  level:
#    org:
#      springframework:
#        web: DEBUG
#        http:
#          converter: DEBUG
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order
    username: embarkx
    password: embarkx
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8083


management:
  endpoints:
    web:
      exposure:
        include: '*'

rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest

EUREKA:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true


logging:
  file:
    name: logs/${spring.application.name}.log
  logback:
    rollingpolicy:
      max-file-size: 5MB
      max-history: 30

# Uncomment the following lines to enable H2 database configuration
#h2 database configuration

#spring:
#  datasource:
#    url: jdbc:h2:mem:testdb
#    driver-class-name: org.h2.Driver
#    username: sa
#    password: ""
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true

