---

spring:
  data:
    mongodb:
      uri: ${MONGO_URI}
      database: usersdb

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: TRACE

server:
  port: 8082
#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/userdb
#    username: embarkx
#    password: embarkx
#    jpa:
#      database: POSTGRESQL
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#
#server:
#  port: 8082
#
#logging:
#  level:
#    org.springframework.web: DEBUG
#    org.springframework.http.converter: DEBUG
